### ISSUE TITLE
penambahan validasi fitur search di menu "posts"

### ISSUE THREAD

**Issue by deaaprizal** [deaaprizal/laract9#103]
Fitur search sudah oke, pencarian berdasarkan text postingan.

1 yang belum di validate adalah:
-ketika user mau memunculkan semua postingannya lagi setelah melakukan searching itu belum bisa

tambahan plus:
-input search ketika length lebih dari 3 maka lakukan render langsung (munculkan pencarian) tanpa harus pencet tombol search nya. (seolah realtime) make react js ini simpel karena trigger by "onChange" dari input nya.

thank u 👍

**Comment by Fadlar** [comment]
boleh nih, tpi gapake length bang. diwaktu aja jadi ketika user ga ngetik 500ms baru render (melakukan pencarian)
