### ISSUE TITLE
penambahan fitur pencarian di menu "PENGGUNA"

### ISSUE THREAD

**Issue by deaaprizal** [deaaprizal/laract9#104]
task available:
1. menambahkan fitur pencarian di menu pengguna
2. termasuk validasi

**Comment by xrafffcode** [comment]
Ezz inimah, otw bikin

**Comment by deaaprizal** [comment]
> Ezz inimah, otw bikin

anjaayy di edankeun, gas breee banyak kerjaan wwkwk
