### ISSUE TITLE
BUGFIX postingan di menu author

### ISSUE THREAD

**Issue by deaaprizal** [deaaprizal/laract9#109]
postingan di menu author tidak muncul tanggal postingnya. sebelumnya muncul, tapi sekarang tidak.

gak ke cek sama gue kwkw.

contoh author page:
https://cuyuniverse.co/author/deaafrizal

**Comment by xrafffcode** [comment]
okee shap

**Comment by xrafffcode** [comment]
![image](https://user-images.githubusercontent.com/70202056/180633142-d3748e0f-e9f7-4943-a8f9-bfc43e67c4d4.png)
udah fix bang

**Comment by INJITZY** [comment]
Gg
