### ISSUE TITLE
Placeholder dark mode tidak menampilkan value text

### ISSUE THREAD

**Issue by wahmulyadi** [deaaprizal/laract9#126]
ada beberapa placeholder di dark mode yang value text nya gk kebaca nih brother. mungkin bisa di style lagi di next update. kayak pas mau komen sama buat post

**Comment by deaaprizal** [comment]
betul, setelah cek cek ternyata iya dark mode belum merata 🌼

**Comment by deaaprizal** [comment]
@wahmulyadi tolong di list bro temuan bug nya ya, thank u loh 😍 langsung masukin sebagai issues aja yaa

**Comment by wahmulyadi** [comment]
oke @deaaprizal , sorry lagi gk bisa bantu fixing, lagi ada yang dipegang juga soalnya. nanti ku cek lagi ada yang aneh lagi atau engga

**Comment by xrafffcode** [comment]
> @wahmulyadi tolong di list bro temuan bug nya ya, thank u loh 😍 langsung masukin sebagai issues aja yaa

https://github.com/deaaprizal/laract9/pull/128
udah aman ya a

**Comment by deaaprizal** [comment]
jossss
