### ISSUE TITLE
Docker Image Untuk Setup Dev Environment

### ISSUE THREAD

**Issue by LittleQuartZ** [deaaprizal/laract9#159]
sesuai judul, setup dev environment dengan docker akan lebih mudah

**Comment by deaaprizal** [comment]
> sesuai judul, setup dev environment dengan docker akan lebih mudah

belum bisa ready karena belum siapin kubernetes dan registry di sisi server.

**Comment by deaaprizal** [comment]
ini gue close ya, dimasukan ke discussion aja thank u 👍
