### ISSUE TITLE
Pagination bug on mobile web

### ISSUE THREAD

**Issue by faruqmaulana** [deaaprizal/laract9#176]
![image](https://user-images.githubusercontent.com/88839109/180824373-032bda7f-4b54-4489-80c9-f49c932c39cf.png)

**Comment by deaaprizal** [comment]
> ![image](https://user-images.githubusercontent.com/88839109/180824373-032bda7f-4b54-4489-80c9-f49c932c39cf.png)

UI itu woy bukan bug, tapi nyangeyeng alias terbang kesaana kemari 🤣🤣🤣

**Comment by faruqmaulana** [comment]
oiya bang lupa wkwkwk, pokoknya mah itu dah 😅
