### ISSUE TITLE
Replace paginate to cursorPaginate

### ISSUE THREAD

**Issue by novalramdhani** [deaaprizal/laract9#183]
Terkait performa kang, kenapa ngga pake `cursorPaginate` daripada paginate biasa.

**Comment by deaaprizal** [comment]
gw belum nyentuh paginate lagi bro, lupa terahir siapa itu ya

**Comment by novalramdhani** [comment]
> gw belum nyentuh paginate lagi bro, lupa terahir siapa itu ya

Boleh tuh, di update kang wkwkwkkw
