### ISSUE TITLE
Sedikit kesalahan pada index element

### ISSUE THREAD

**Issue by eksa-arifa** [deaaprizal/laract9#198]
Index element indikasi online dan offline,di pojok kanan atas profile user, di list user ,lebih tinggi dibanding navbar

**Comment by ZihxS** [comment]
ini PR nya cuy: https://github.com/deaaprizal/laract9/pull/193

**Comment by eksa-arifa** [comment]
> ini PR nya cuy: #193

Cara bantu perbaikin gimana ya

**Comment by eksa-arifa** [comment]
> ini PR nya cuy: #193

Nggak terlalu paham tentang github gw
