### ISSUE TITLE
Bug white line

### ISSUE THREAD

**Issue by vinoaryo** [deaaprizal/laract9#219]
# Ada garis putih di paling bawah web di mode desktop
![image](https://user-images.githubusercontent.com/73981680/181454129-52110598-71d6-4596-bcea-ccd8664e1f79.png)

**Comment by faruqmaulana** [comment]
aman bang, udah saya pull request tinggal nunggu bang dea

**Comment by vinoaryo** [comment]
> aman bang, udah saya pull request tinggal nunggu bang dea

Mantap
