### ISSUE TITLE
SMPTP is not defined

### ISSUE THREAD

**Issue by billalxcode** [deaaprizal/laract9#235]
Selamat sore, saya ingin melaporkan bug pada CUY UNIVERSE.

Bug ini aktif ketika user mendaftar dan saat mendaftar akan muncul error seperti dibawah:

![Screenshot 2022-07-31 at 15-40-31 CUYUNIVERSE - CUY UNIVERSE](https://user-images.githubusercontent.com/71764176/182018911-ccb67aa4-45f1-4304-9731-a7da9306a733.png)

Btw saya run di lokal. Jika ini kesalahan saat running mohon beritahu bagaimana cara memperbaiki nya dan jika ini kesalahan dari sistem maka akan saya coba perbaiki bug ini.

Thanks,

**Comment by kbiits** [comment]
Bantu jawab, ini kesalahan di local ya, silahkan isi .env smtp nya biar jalan email nya. Untuk test di local, saya sendiri biasanya pake mailtrap.io buat test email

**Comment by AsfahanX** [comment]
atau, kalo cuma mau test di lokal tanpa setup smtp, class User.php nya diubah dulu sementara cuy

https://github.com/deaaprizal/laract9/blob/b0a56e5656bda56597f1607613f7a225bd946958/app/Models/User.php#L11-L12

**Comment by deaaprizal** [comment]
sudah terjawab ya? issues closed thank u 👍
